### ISSUE TITLE
Error when running pip install

### ISSUE THREAD

**Issue by michaelvenable** [coreyfournier/PoolAutomation#1]
I get an error regarding version dependencies when running pip install.

**To Reproduce**
1. Install Python 3.10.10.
2. Run `python -m -pip install -r requirements.txt` from the VS Code terminal.

**Observed Behavior**

The error below is shown.

```bash
> python -m pip install -r requirements.txt
Collecting CherryPy==18.6.1
  Using cached CherryPy-18.6.1-py2.py3-none-any.whl (419 kB)
Collecting dataclasses_json==0.5.7
  Using cached dataclasses_json-0.5.7-py3-none-any.whl (25 kB)
Collecting dataclass_wizard==0.22.2
  Using cached dataclass_wizard-0.22.2-py2.py3-none-any.whl (90 kB)
Collecting dataclasses==0.6
  Using cached dataclasses-0.6-py3-none-any.whl (14 kB)
Collecting smbus2==0.4.2
  Using cached smbus2-0.4.2-py2.py3-none-any.whl (11 kB)
Collecting adafruit-circuitpython-ssd1306==2.12.12
  Using cached adafruit_circuitpython_ssd1306-2.12.12-py3-none-any.whl (7.6 kB)
Collecting pillow==9.4.0
  Using cached Pillow-9.4.0-cp310-cp310-win_amd64.whl (2.5 MB)
Collecting board==1.0
  Using cached board-1.0-py2.py3-none-any.whl (12 kB)
Collecting pyodbc==4.0.35
  Using cached pyodbc-4.0.35-cp310-cp310-win_amd64.whl (66 kB)
ERROR: Ignored the following versions that require a different python version: 0.7 Requires-Python >=3.6, <3.7; 0.8 Requires-Python >=3.6, <3.7
ERROR: Could not find a version that satisfies the requirement odata-query==2.8.2 (from versions: 0.4.0, 0.4.1, 0.4.2, 0.5.0, 0.5.1, 0.5.2, 0.6.0b1, 0.6.0, 0.7.0, 0.7.1, 0.7.2, 0.8.0, 0.8.1)
ERROR: No matching distribution found for odata-query==2.8.2
```

**Comment by coreyfournier** [comment]
Not sure where i got that version from. My laptop had 0.8.0. I updated the
angular-ui branch with the fix.

I would have noticed this when building the docker image, but I can't use
that package on the pi, i have to build the wheels from scratch.

**Comment by coreyfournier** [comment]
Resolved in the angular branch using platform target pip environment variables.

smbus2==0.4.2 ; sys_platform == "linux" and platform_machine == "armv7l"
adafruit-circuitpython-ssd1306==2.12.12 ; sys_platform == "linux" and platform_machine == "armv7l"

**Comment by coreyfournier** [comment]
Resolved in the angular branch using platform target pip environment variables.

smbus2==0.4.2 ; sys_platform == "linux" and platform_machine == "armv7l"
adafruit-circuitpython-ssd1306==2.12.12 ; sys_platform == "linux" and platform_machine == "armv7l"
